swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth/google/login:
        get:
            tags:
                - Auth
            summary: Google login Auth
            description: Initiates the Google OAuth 2.0 login flow by redirecting to the Google authorization endpoint.
            operationId: Auth#Google login
            responses:
                "307":
                    description: Temporary Redirect response.
            schemes:
                - http
    /auth/google/logout:
        get:
            tags:
                - Auth
            summary: Google logout Auth
            description: Logs the user out by clearing the session and redirecting to the appropriate post-logout URL.
            operationId: Auth#Google logout
            responses:
                "307":
                    description: Temporary Redirect response.
            schemes:
                - http
    /auth/me:
        get:
            tags:
                - Auth
            summary: Me Auth
            description: Returns information about the currently authenticated user.
            operationId: Auth#Me
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccountUser'
                        required:
                            - id
                            - email
                            - firstName
                            - lastNames
                            - remainingNames
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/AccountUser'
                        required:
                            - id
                            - email
                            - firstName
                            - lastNames
                            - remainingNames
            schemes:
                - http
    /courses:
        get:
            tags:
                - course
            summary: get_all_courses course
            description: Get all courses, only admin can use this method
            operationId: course#get_all_courses
            parameters:
                - name: get_all_courses_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CourseGetAllCoursesRequestBody'
                    required:
                        - page
                        - limit
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Course'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/CourseGetAllCoursesBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/CourseGetAllCoursesUnAuthorizedResponseBody'
            schemes:
                - http
    /courses/available:
        get:
            tags:
                - course
            summary: get_user_available_courses course
            description: Get all courses available for the user, only user can use this method
            operationId: course#get_user_available_courses
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Course'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/CourseGetUserAvailableCoursesBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/CourseGetUserAvailableCoursesUnAuthorizedResponseBody'
            schemes:
                - http
    /courses/upload:
        post:
            tags:
                - course
            summary: upload_all_courses course
            description: Upload all courses from data of file, only admin can use this method
            operationId: course#upload_all_courses
            parameters:
                - name: upload_all_courses_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UploadAllCoursesPayload'
                    required:
                        - courses
            responses:
                "201":
                    description: Created response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/CourseUploadAllCoursesBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/CourseUploadAllCoursesUnAuthorizedResponseBody'
            schemes:
                - http
    /enrollment/enroll:
        post:
            tags:
                - enrollment
            summary: enroll enrollment
            description: Enroll an student in selected courses
            operationId: enrollment#enroll
            parameters:
                - name: EnrollRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EnrollmentPayload'
                    required:
                        - enrollCourses
            responses:
                "201":
                    description: Created response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/EnrollmentEnrollBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/EnrollmentEnrollUnAuthorizedResponseBody'
            schemes:
                - http
    /enrollment/enrollement_courses:
        post:
            tags:
                - enrollment
            summary: get_enrollment_courses enrollment
            description: Get all courses enrolled by an attendee
            operationId: enrollment#get_enrollment_courses
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EnrollmentPayload'
                        required:
                            - enrollCourses
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/EnrollmentGetEnrollmentCoursesBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/EnrollmentGetEnrollmentCoursesUnAuthorizedResponseBody'
            schemes:
                - http
    /google/callback:
        get:
            tags:
                - Auth
            summary: GoogleCallback Auth
            description: Google OAuth callback. Creates or reuses a session and redirects to the frontend.
            operationId: Auth#GoogleCallback
            responses:
                "307":
                    description: Temporary Redirect response.
                "401":
                    description: Unauthorized response.
            schemes:
                - http
    /oauth/login:
        post:
            tags:
                - oauth
            summary: login oauth
            description: Login using OAuth with a specific provider
            operationId: oauth#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/OauthLoginRequestBody'
                    required:
                        - oauth_provider_id
                        - code
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserOauthInfo'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/OauthLoginUnauthorizedResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/OauthLoginNotFoundResponseBody'
            schemes:
                - http
definitions:
    AccountUser:
        title: AccountUser
        type: object
        properties:
            email:
                type: string
                description: User email
                example: Sed nam facere accusantium architecto nihil dolorum.
            firstName:
                type: string
                description: User first name
                example: Eaque sed voluptatem.
            id:
                type: string
                description: Unique user ID
                example: Est totam aut deleniti culpa ut.
            lastNames:
                type: string
                description: User last names
                example: Expedita nisi consequatur debitis nobis.
            remainingNames:
                type: string
                description: User remaining names
                example: Eos odio.
        example:
            email: Quis nobis dolor molestiae qui.
            firstName: Qui soluta voluptate pariatur et.
            id: Ut incidunt commodi ut in.
            lastNames: Porro illo fugit sed accusantium nulla.
            remainingNames: Natus similique iure adipisci nobis ut.
        required:
            - id
            - email
            - firstName
            - lastNames
            - remainingNames
    Course:
        title: Course
        type: object
        properties:
            cicle_number:
                type: integer
                description: Cicle number of the course
                example: 1
                format: int64
                minimum: 1
            credits:
                type: integer
                description: Number of credits for the course
                example: 3
                format: int64
                minimum: 1
            id:
                type: string
                description: Unique identifier for the course
                example: "144"
            name:
                type: string
                description: Name of the course
                example: Introduction to Programming
                minLength: 1
                maxLength: 128
        description: Course represents a course in the system
        example:
            cicle_number: 1
            credits: 3
            id: "144"
            name: Introduction to Programming
        required:
            - id
            - name
            - credits
            - cicle_number
    CourseGetAllCoursesBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CourseGetAllCoursesRequestBody:
        title: CourseGetAllCoursesRequestBody
        type: object
        properties:
            limit:
                type: integer
                description: Number of items per page
                default: 10
                example: 1721943592985976132
                format: int64
                minimum: 1
            page:
                type: integer
                description: Page number for pagination
                default: 1
                example: 1887344485657052791
                format: int64
                minimum: 1
        example:
            limit: 5604433874485064464
            page: 639707977616588691
        required:
            - page
            - limit
    CourseGetAllCoursesUnAuthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized access (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CourseGetUserAvailableCoursesBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CourseGetUserAvailableCoursesUnAuthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Unauthorized access (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CoursePayload:
        title: CoursePayload
        type: object
        properties:
            cicle_number:
                type: integer
                description: Cicle number of the course
                example: 1
                format: int64
                minimum: 1
            credits:
                type: integer
                description: Number of credits for the course
                example: 3
                format: int64
                minimum: 1
            name:
                type: string
                description: Name of the course
                example: Introduction to Programming
                minLength: 1
                maxLength: 128
        description: Payload for uploading a single course
        example:
            cicle_number: 1
            credits: 3
            name: Introduction to Programming
        required:
            - name
            - credits
            - cicle_number
    CourseUploadAllCoursesBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CourseUploadAllCoursesUnAuthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized access (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollCourseType:
        title: EnrollCourseType
        type: object
        properties:
            course_id:
                type: integer
                description: Course ID
                example: 694091412
                format: int32
            id:
                type: integer
                description: Enrollment ID
                example: 1368988241
                format: int32
            program_id:
                type: integer
                description: Program ID
                example: 1311934067
                format: int32
        description: Represents a course enrollment
        example:
            course_id: 1728305637
            id: 668033071
            program_id: 1111042991
        required:
            - id
            - course_id
            - program_id
    EnrollmentEnrollBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentEnrollUnAuthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Unauthorized access (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentGetEnrollmentCoursesBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentGetEnrollmentCoursesUnAuthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Unauthorized access (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentPayload:
        title: EnrollmentPayload
        type: object
        properties:
            enrollCourses:
                type: array
                items:
                    $ref: '#/definitions/EnrollCourseType'
                description: Attendee ID
                example:
                    - course_id: 2072469154
                      id: 1959792023
                      program_id: 1795971965
                    - course_id: 2072469154
                      id: 1959792023
                      program_id: 1795971965
                    - course_id: 2072469154
                      id: 1959792023
                      program_id: 1795971965
                    - course_id: 2072469154
                      id: 1959792023
                      program_id: 1795971965
        example:
            enrollCourses:
                - course_id: 2072469154
                  id: 1959792023
                  program_id: 1795971965
                - course_id: 2072469154
                  id: 1959792023
                  program_id: 1795971965
                - course_id: 2072469154
                  id: 1959792023
                  program_id: 1795971965
                - course_id: 2072469154
                  id: 1959792023
                  program_id: 1795971965
        required:
            - enrollCourses
    OauthLoginNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Not registered provider (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OauthLoginRequestBody:
        title: OauthLoginRequestBody
        type: object
        properties:
            code:
                type: string
                description: OAuth code given by the provider
                example: 1gt
                minLength: 10
            oauth_provider_id:
                type: integer
                description: ID of the OAuth provider
                example: 3939126529778815486
                format: int64
                minimum: 1
        example:
            code: 7q1
            oauth_provider_id: 4556976093100302847
        required:
            - oauth_provider_id
            - code
    OauthLoginUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid or expired code (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UploadAllCoursesPayload:
        title: UploadAllCoursesPayload
        type: object
        properties:
            courses:
                type: array
                items:
                    $ref: '#/definitions/CoursePayload'
                example:
                    - cicle_number: 1
                      credits: 3
                      name: Introduction to Programming
                    - cicle_number: 1
                      credits: 3
                      name: Introduction to Programming
        example:
            courses:
                - cicle_number: 1
                  credits: 3
                  name: Introduction to Programming
                - cicle_number: 1
                  credits: 3
                  name: Introduction to Programming
                - cicle_number: 1
                  credits: 3
                  name: Introduction to Programming
        required:
            - courses
    UserOauthInfo:
        title: UserOauthInfo
        type: object
        properties:
            oauth_provider_id:
                type: integer
                description: ID of the provider used
                example: 1
                format: int64
                minimum: 1
            profile_picture:
                type: string
                description: Profile picture URL
                example: https://avatars.githubusercontent.com/u/123456?v=4
                format: uri
            provider_user_id:
                type: string
                description: Access token given by the provider
                example: ya29.a0AfH6SM...
                minLength: 10
        example:
            oauth_provider_id: 1
            profile_picture: https://avatars.githubusercontent.com/u/123456?v=4
            provider_user_id: ya29.a0AfH6SM...
