openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for course
paths:
    /auth/google/login:
        get:
            tags:
                - Auth
            summary: Google login Auth
            description: Initiates the Google OAuth 2.0 login flow by redirecting to the Google authorization endpoint.
            operationId: Auth#Google login
            responses:
                "307":
                    description: Temporary Redirect response.
    /auth/google/logout:
        get:
            tags:
                - Auth
            summary: Google logout Auth
            description: Logs the user out by clearing the session and redirecting to the appropriate post-logout URL.
            operationId: Auth#Google logout
            responses:
                "307":
                    description: Temporary Redirect response.
    /auth/me:
        get:
            tags:
                - Auth
            summary: Me Auth
            description: Returns information about the currently authenticated user.
            operationId: Auth#Me
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountUser'
                            example:
                                email: Perferendis vel et quidem.
                                firstName: Libero quidem ut numquam incidunt incidunt.
                                id: Aut commodi magni et debitis blanditiis.
                                lastNames: Non consectetur id.
                                remainingNames: Harum voluptas impedit.
                "401":
                    description: Unauthorized response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountUser'
                            example:
                                email: Tempore amet aspernatur facilis.
                                firstName: Consequatur et facere alias.
                                id: Amet assumenda voluptatem molestiae quisquam.
                                lastNames: Laboriosam dicta rerum dolore.
                                remainingNames: Sed delectus.
    /courses:
        get:
            tags:
                - course
            summary: get_all_courses course
            description: Get all courses, only admin can use this method
            operationId: course#get_all_courses
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetAllCoursesRequestBody'
                        example:
                            limit: 8763346776882884684
                            page: 651642441213013619
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Course'
                                example:
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                            example:
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                "400":
                    description: 'bad_request: Invalid request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'un_authorized: Unauthorized access'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /courses/available:
        get:
            tags:
                - course
            summary: get_user_available_courses course
            description: Get all courses available for the user, only user can use this method
            operationId: course#get_user_available_courses
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Course'
                                example:
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                                    - cicle_number: 1
                                      credits: 3
                                      id: "144"
                                      name: Introduction to Programming
                            example:
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  id: "144"
                                  name: Introduction to Programming
                "400":
                    description: 'bad_request: Invalid request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'un_authorized: Unauthorized access'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /courses/upload:
        post:
            tags:
                - course
            summary: upload_all_courses course
            description: Upload all courses from data of file, only admin can use this method
            operationId: course#upload_all_courses
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UploadAllCoursesPayload'
                        example:
                            courses:
                                - cicle_number: 1
                                  credits: 3
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  name: Introduction to Programming
                                - cicle_number: 1
                                  credits: 3
                                  name: Introduction to Programming
            responses:
                "201":
                    description: Created response.
                "400":
                    description: 'bad_request: Invalid request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'un_authorized: Unauthorized access'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /enrollment/enroll:
        post:
            tags:
                - enrollment
            summary: enroll enrollment
            description: Enroll an student in selected courses
            operationId: enrollment#enroll
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EnrollmentPayload'
                        example:
                            enrollCourses:
                                - course_id: 2072469154
                                  id: 1959792023
                                  program_id: 1795971965
                                - course_id: 2072469154
                                  id: 1959792023
                                  program_id: 1795971965
            responses:
                "201":
                    description: Created response.
                "400":
                    description: 'bad_request: Invalid request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'un_authorized: Unauthorized access'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /enrollment/enrollement_courses:
        post:
            tags:
                - enrollment
            summary: get_enrollment_courses enrollment
            description: Get all courses enrolled by an attendee
            operationId: enrollment#get_enrollment_courses
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnrollmentPayload'
                            example:
                                enrollCourses:
                                    - course_id: 1563078851
                                      id: 127321437
                                      program_id: 1855439970
                                    - course_id: 1563078851
                                      id: 127321437
                                      program_id: 1855439970
                "400":
                    description: 'bad_request: Invalid request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'un_authorized: Unauthorized access'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /google/callback:
        get:
            tags:
                - Auth
            summary: GoogleCallback Auth
            description: Google OAuth callback. Creates or reuses a session and redirects to the frontend.
            operationId: Auth#GoogleCallback
            responses:
                "307":
                    description: Temporary Redirect response.
                "401":
                    description: Unauthorized response.
    /oauth/login:
        post:
            tags:
                - oauth
            summary: login oauth
            description: Login using OAuth with a specific provider
            operationId: oauth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            code: ryc
                            oauth_provider_id: 5959512667628956629
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserOauthInfo'
                            example:
                                oauth_provider_id: 1
                                profile_picture: https://avatars.githubusercontent.com/u/123456?v=4
                                provider_user_id: ya29.a0AfH6SM...
                "401":
                    description: 'unauthorized: Invalid or expired code'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not registered provider'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        AccountUser:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Asperiores quia sit inventore recusandae unde est.
                firstName:
                    type: string
                    description: User first name
                    example: Corrupti neque est aut earum minima.
                id:
                    type: string
                    description: Unique user ID
                    example: Et eveniet deserunt iure est et recusandae.
                lastNames:
                    type: string
                    description: User last names
                    example: Neque exercitationem.
                remainingNames:
                    type: string
                    description: User remaining names
                    example: Adipisci cumque.
            description: AccountUser type
            example:
                email: Repellendus iste facere alias.
                firstName: Illo soluta iure cupiditate rerum.
                id: Voluptate delectus.
                lastNames: Amet quae qui ea voluptas omnis voluptatum.
                remainingNames: Porro quo.
            required:
                - id
                - email
                - firstName
                - lastNames
                - remainingNames
        Course:
            type: object
            properties:
                cicle_number:
                    type: integer
                    description: Cicle number of the course
                    example: 1
                    format: int64
                    minimum: 1
                credits:
                    type: integer
                    description: Number of credits for the course
                    example: 3
                    format: int64
                    minimum: 1
                id:
                    type: string
                    description: Unique identifier for the course
                    example: "144"
                name:
                    type: string
                    description: Name of the course
                    example: Introduction to Programming
                    minLength: 1
                    maxLength: 128
            description: Course represents a course in the system
            example:
                cicle_number: 1
                credits: 3
                id: "144"
                name: Introduction to Programming
            required:
                - id
                - name
                - credits
                - cicle_number
        CoursePayload:
            type: object
            properties:
                cicle_number:
                    type: integer
                    description: Cicle number of the course
                    example: 1
                    format: int64
                    minimum: 1
                credits:
                    type: integer
                    description: Number of credits for the course
                    example: 3
                    format: int64
                    minimum: 1
                name:
                    type: string
                    description: Name of the course
                    example: Introduction to Programming
                    minLength: 1
                    maxLength: 128
            description: Payload for uploading a single course
            example:
                cicle_number: 1
                credits: 3
                name: Introduction to Programming
            required:
                - name
                - credits
                - cicle_number
        EnrollCourseType:
            type: object
            properties:
                course_id:
                    type: integer
                    description: Course ID
                    example: 788130116
                    format: int32
                id:
                    type: integer
                    description: Enrollment ID
                    example: 966818887
                    format: int32
                program_id:
                    type: integer
                    description: Program ID
                    example: 1706285241
                    format: int32
            description: Represents a course enrollment
            example:
                course_id: 521787374
                id: 1141416709
                program_id: 1128923607
            required:
                - id
                - course_id
                - program_id
        EnrollmentPayload:
            type: object
            properties:
                enrollCourses:
                    type: array
                    items:
                        $ref: '#/components/schemas/EnrollCourseType'
                    description: Attendee ID
                    example:
                        - course_id: 1370333918
                          id: 1876751260
                          program_id: 1801666353
                        - course_id: 1370333918
                          id: 1876751260
                          program_id: 1801666353
                        - course_id: 1370333918
                          id: 1876751260
                          program_id: 1801666353
                        - course_id: 1370333918
                          id: 1876751260
                          program_id: 1801666353
            description: Input data to enroll an attendee in a courses
            example:
                enrollCourses:
                    - course_id: 1370333918
                      id: 1876751260
                      program_id: 1801666353
                    - course_id: 1370333918
                      id: 1876751260
                      program_id: 1801666353
                    - course_id: 1370333918
                      id: 1876751260
                      program_id: 1801666353
            required:
                - enrollCourses
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Invalid request
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        EventCourse:
            type: object
            properties:
                end_date:
                    type: integer
                    description: End date of the course in the event in Unix timestamp format
                    example: 1748992994154
                    format: int64
                id:
                    type: string
                    description: Unique identifier for the event course
                    example: "144"
                instalation:
                    $ref: '#/components/schemas/InstalatitonCoursePayload'
                start_date:
                    type: integer
                    description: Start date of the course in the event in Unix timestamp format
                    example: 1748992994154
                    format: int64
            description: Is the schedule of the course in the event
            example:
                end_date: 1748992994154
                id: "144"
                instalation:
                    description: This course is in Sistem Ingenier School
                    name: Sistem Ingenier School
                start_date: 1748992994154
            required:
                - id
                - start_date
                - end_date
                - instalation
        EventCoursePayload:
            type: object
            properties:
                end_date:
                    type: integer
                    description: End date of the course in the event in Unix timestamp format
                    example: 1748992994154
                    format: int64
                instalation:
                    $ref: '#/components/schemas/InstalatitonCoursePayload'
                start_date:
                    type: integer
                    description: Start date of the course in the event in Unix timestamp format
                    example: 1748992994154
                    format: int64
            description: Is the schedule of the course in the event
            example:
                end_date: 1748992994154
                instalation:
                    description: This course is in Sistem Ingenier School
                    name: Sistem Ingenier School
                start_date: 1748992994154
            required:
                - start_date
                - end_date
                - instalation
        GetAllCoursesRequestBody:
            type: object
            properties:
                limit:
                    type: integer
                    description: Number of items per page
                    default: 10
                    example: 8391230746189424457
                    format: int64
                    minimum: 1
                page:
                    type: integer
                    description: Page number for pagination
                    default: 1
                    example: 217600928582578569
                    format: int64
                    minimum: 1
            example:
                limit: 3762092386063130846
                page: 7554876649250573982
            required:
                - page
                - limit
        InstalatitonCourse:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the instalation of course
                    example: This course is in Sistem Ingenier School
                    minLength: 1
                    maxLength: 512
                id:
                    type: integer
                    description: Unique identifier for the installation of the course
                    example: 144
                    format: int64
                name:
                    type: string
                    description: Name of the place where the course is installed
                    example: Sistem Ingenier School
                    minLength: 1
                    maxLength: 128
            description: Represents a course in the installation process
            example:
                description: This course is in Sistem Ingenier School
                id: 144
                name: Sistem Ingenier School
            required:
                - id
                - name
                - description
        InstalatitonCoursePayload:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the instalation of course
                    example: This course is in Sistem Ingenier School
                    minLength: 1
                    maxLength: 512
                name:
                    type: string
                    description: Name of the place where the course is installed
                    example: Sistem Ingenier School
                    minLength: 1
                    maxLength: 128
            description: Represents a course in the installation process
            example:
                description: This course is in Sistem Ingenier School
                name: Sistem Ingenier School
            required:
                - name
                - description
        LoginRequestBody:
            type: object
            properties:
                code:
                    type: string
                    description: OAuth code given by the provider
                    example: duu
                    minLength: 10
                oauth_provider_id:
                    type: integer
                    description: ID of the OAuth provider
                    example: 123508098179586258
                    format: int64
                    minimum: 1
            example:
                code: 9ju
                oauth_provider_id: 6325836094469841994
            required:
                - oauth_provider_id
                - code
        OAuthProvider:
            type: object
            properties:
                auth_url:
                    type: string
                    description: Provider authentication URL
                    example: https://accounts.google.com/o/oauth2/auth
                    format: uri
                id:
                    type: integer
                    description: unique identifier
                    example: 1
                    format: int64
                    minimum: 1
                name:
                    type: string
                    description: Intern provider name
                    example: google
                    minLength: 2
            description: registered provider in th system
            example:
                auth_url: https://accounts.google.com/o/oauth2/auth
                id: 1
                name: google
            required:
                - id
                - name
                - auth_url
        SpeakerCoursePayload:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Et dolores.
                firstName:
                    type: string
                    description: User first name
                    example: Laudantium quia error sunt illum rerum.
                id:
                    type: string
                    description: Unique user ID
                    example: Sed et.
                lastNames:
                    type: string
                    description: User last names
                    example: Dolorem iusto iusto minima.
                remainingNames:
                    type: string
                    description: User remaining names
                    example: Similique accusantium odio dolor accusamus labore consequuntur.
            example:
                email: Sunt sit excepturi exercitationem.
                firstName: Maxime omnis aut ipsam accusamus odio accusantium.
                id: Aut vitae nihil.
                lastNames: Itaque accusantium magnam in.
                remainingNames: Beatae id aut quo reiciendis commodi.
            required:
                - id
                - email
                - firstName
                - lastNames
                - remainingNames
        TuitionCourse:
            type: object
            properties:
                events:
                    type: array
                    items:
                        $ref: '#/components/schemas/EventCoursePayload'
                    example:
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                id:
                    type: string
                    description: Unique identifier for the tuition course
                    example: "144"
                taken_places:
                    type: integer
                    description: Number of places already taken in the course
                    example: 10
                    format: int64
                    minimum: 0
                total_places:
                    type: integer
                    description: Total number of places available for the course
                    example: 30
                    format: int64
                    minimum: 1
            description: Tuition details of the course
            example:
                events:
                    - end_date: 1748992994154
                      instalation:
                        description: This course is in Sistem Ingenier School
                        name: Sistem Ingenier School
                      start_date: 1748992994154
                    - end_date: 1748992994154
                      instalation:
                        description: This course is in Sistem Ingenier School
                        name: Sistem Ingenier School
                      start_date: 1748992994154
                    - end_date: 1748992994154
                      instalation:
                        description: This course is in Sistem Ingenier School
                        name: Sistem Ingenier School
                      start_date: 1748992994154
                id: "144"
                taken_places: 10
                total_places: 30
            required:
                - id
                - tuition
                - currency
        TuitionCoursePayload:
            type: object
            properties:
                events:
                    type: array
                    items:
                        $ref: '#/components/schemas/EventCoursePayload'
                    example:
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                        - end_date: 1748992994154
                          instalation:
                            description: This course is in Sistem Ingenier School
                            name: Sistem Ingenier School
                          start_date: 1748992994154
                taken_places:
                    type: integer
                    description: Number of places already taken in the course
                    example: 10
                    format: int64
                    minimum: 0
                total_places:
                    type: integer
                    description: Total number of places available for the course
                    example: 30
                    format: int64
                    minimum: 1
            description: Tuition details of the course
            example:
                events:
                    - end_date: 1748992994154
                      instalation:
                        description: This course is in Sistem Ingenier School
                        name: Sistem Ingenier School
                      start_date: 1748992994154
                    - end_date: 1748992994154
                      instalation:
                        description: This course is in Sistem Ingenier School
                        name: Sistem Ingenier School
                      start_date: 1748992994154
                taken_places: 10
                total_places: 30
            required:
                - tuition
                - currency
        UploadAllCoursesPayload:
            type: object
            properties:
                courses:
                    type: array
                    items:
                        $ref: '#/components/schemas/CoursePayload'
                    example:
                        - cicle_number: 1
                          credits: 3
                          name: Introduction to Programming
                        - cicle_number: 1
                          credits: 3
                          name: Introduction to Programming
            description: Payload for uploading all courses
            example:
                courses:
                    - cicle_number: 1
                      credits: 3
                      name: Introduction to Programming
                    - cicle_number: 1
                      credits: 3
                      name: Introduction to Programming
            required:
                - courses
        UserOauthInfo:
            type: object
            properties:
                oauth_provider_id:
                    type: integer
                    description: ID of the provider used
                    example: 1
                    format: int64
                    minimum: 1
                profile_picture:
                    type: string
                    description: Profile picture URL
                    example: https://avatars.githubusercontent.com/u/123456?v=4
                    format: uri
                provider_user_id:
                    type: string
                    description: Access token given by the provider
                    example: ya29.a0AfH6SM...
                    minLength: 10
            description: User information via Oauth
            example:
                oauth_provider_id: 1
                profile_picture: https://avatars.githubusercontent.com/u/123456?v=4
                provider_user_id: ya29.a0AfH6SM...
tags:
    - name: course
      description: Manage the courses to enrollements
    - name: enrollment
      description: Manages attendee enrollment in courses
    - name: oauth
      description: Oauth Authentication service
    - name: Auth
      description: Service to handle authentication and authorization
